### ISSUE TITLE
【功能建议】添加违禁词拒绝转发消息

### ISSUE THREAD

**Issue by XXJNOTFOUND** [17TheWord/nonebot-plugin-mcqq#123]
### 插件版本

MC_QQ

### 插件版本号

2.6.2

### 功能建议

添加像`TrChat`那样的ChatFitter，阻止机器人将恶意信息发送至QQ群导致被举报/封号/群聊被封

### 额外信息（可选）

被人恶意举报了,比如发黄色信息
以及刷屏
详见`https://www.wtfxxj.top/d/57`
(图片无法放大很抱歉，但是可以看出就是这么刷屏/发恶意消息导致机器人被风

**Comment by XXJNOTFOUND** [comment]
希望添加TrChat那样的聊天规律[https://trchat.trixey.cc/]
因为这里有现成的违禁词列表,大约几千个
```yaml
Cloud-Thesaurus:
  Enabled: true
  # 忽略词库中的内容
  Ignored: ['nt'] 
  # 词库地址
  Urls: 
    - 'https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json'
    - 'https://raw.githubusercontent.com/konsheng/Sensitive-lexicon/main/ThirdPartyCompatibleFormats/TrChat/SensitiveLexicon.json'
```
